"""Add dates and status to projects and tasks

Revision ID: c70ac89a3caf
Revises: 7baafa653cb5
Create Date: 2026-05-09 23:00:05.408510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70ac89a3caf'
down_revision: Union[str, Sequence[str], None] = '7baafa653cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('estimation_date', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('closed_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('estimation_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('closed_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'closed_date')
    op.drop_column('tasks', 'estimation_date')
    op.drop_column('tasks', 'start_date')
    op.drop_column('projects', 'closed_date')
    op.drop_column('projects', 'estimation_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
